### ISSUE TITLE
Docs: Using Mumble docker container behind Traefik (reverse proxy) with Let's Encrypt

### ISSUE THREAD

**Issue by flokoe** [PHLAK/docker-mumble#15]
Hi,

this is not really an issue, but more of small guide how to use Mumble docker container behind Traefik.
In the last few days I experimented to use Mumble behind Traefik and I though this might be helpful to others and if there is the need this can be integrated in the docs of this project.

So in case you want to use Mumble behind Traefik here are my simple example configs using Docker Compose.

I am sure you can translate these settings to something like Kubernetes using Traefik as ingress controller.

**`traefik.yml` (static config):**

```yml
# Use docker as provider.
providers:
  docker: {}

# Define two entry points in Traefik. One for UDP and one for TCP.
# If you need more entry points like port 80/443 you need to define them here as well.
entryPoints:
  mumble_udp:
    address: ":64738/udp"
  mumble_tcp:
    address: ":64738"
``` 

**`docker-compose.yml`:**

```yml
version: '3'

services:
  traefik:
    image: traefik:v2.2
    # Expose TCP/UDP port from Traefik container.
    ports:
      - 64738:64738
      - 64738:64738/udp
    volumes:
      # Mount static config for Traefik.
      - ./traefik.yml:/etc/traefik/traefik.yml
      # Let Traefik listen to Docker events.
      - /var/run/docker.sock:/var/run/docker.sock

  mumble:
    image: phlak/mumble
    volumes:
      # Mount entire Let's Encrypt directory from host.
      - /etc/letsencrypt:/le_certs
    labels:
      # Define UDP router called 'mumble' which listens on entry point 'mumble_udp'
      # and proxies requests to service 'mumble'.
      - traefik.udp.routers.mumble.entrypoints=mumble_udp
      - traefik.udp.routers.mumble.service=mumble
      # Tell Traefik to send UDP requests for the service 'mumble' to port 64738 of the container.
      # You don't need to specify the protocol of the port like '64738/udp' as this is detected automatically
      # because we are defining an UDP service.
      - traefik.udp.services.mumble.loadbalancer.server.port=64738

      # Define TCP router called 'mumble' which listens on entry point 'mumble_tcp'
      # and proxies requests to service 'mumble'.
      - traefik.tcp.routers.mumble.entrypoints=mumble_tcp
      - traefik.tcp.routers.mumble.service=mumble
      # A TCP router needs a hostname to listen to.
      - traefik.tcp.routers.mumble.rule=HostSNI(`mumble.example.com`)
      # Tell Traefik to send TCP requests for service 'mumble' to port 64738 of the container.
      - traefik.tcp.services.mumble.loadbalancer.server.port=64738
      # As TCP routers always try to terminate SSL/TLS traffic, but Mumble does this by itself
      # tell the TCP router to pass encrypted traffic to the service directly.
      - traefik.tcp.routers.mumble.tls.passthrough=true
```

As Mumble always encrypts traffic by itself and Traefik saves its certificates in a JSON file you can't use the certificate resolver from Traefik.

So you still have to install Certbot on the host or in a separate container and mount the Let's Encrypt directory into the mumble container or use your own certificates.

Furthermore, for Let's Encrypt to work, you have to change some permissions:

```bash
chown root:1000 /etc/letsencrypt/archive /etc/letsencrypt/live
chmod 750 /etc/letsencrypt/archive /etc/letsencrypt/live

chown root:1000 /etc/letsencrypt/archive/mumble.example.com/privkey*.pem
chmod 640 /etc/letsencrypt/archive/mumble.example.com/privkey*.pem
```

I tried to be as strict as possible to not expose the private keys to the world.

To automatically reload the certificate after a renewal you can simply add a post renewal hook to restart the container:

**`/etc/letsencrypt/renewal-hooks/post/mumble_docker.sh` (Needs `755` as permissions):**

```bash
#!/bin/sh
docker restart id_or_name_of_your_mumble_container
```

I hope someone finds this helpful.

Best regards
Florian
