### ISSUE TITLE
Path file LetsEncrypt

### ISSUE THREAD

**Issue by ghost** [PHLAK/docker-mumble#4]
Hi,

Thank a lot for your job 👍 
But, it's possible to specify de path of certificat for LetsEncrypt on my docker-compose.yml?
Or when I add the information in Dockerfile ?
```
sslCert=/etc/letsencrypt/live/somehost.example.com/fullchain.pem
sslKey=/etc/letsencrypt/live/somehost.example.com/privkey.pem
```

```
version: '3'

services:
  mumble-server:
    build: ./
    container_name: ${CONTAINER_MUMBLE_SERVER}
    restart: unless-stopped
    environment:
      - TZ=UTC
      - VIRTUAL_HOST= ${DOMAINS}
      - LETSENCRYPT_HOST= ${DOMAINS}
      - LETSENCRYPT_EMAIL= ${LETSENCRYPT_EMAIL}
networks:
    default:
       external:
         name: ${NETWORK}
```

For LetsEncrypt, I use : https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion

Thank a lot for your help

Best regards,
